version: "3.9"

services:
  pg:
    image: postgres:16-alpine
    container_name: adpilot_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: adpilot
      POSTGRES_PASSWORD: adpilot
      POSTGRES_DB: adpilot
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adpilot -d adpilot"]
      interval: 3s
      timeout: 2s
      retries: 20

volumes:
  pgdata:
